server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: order
          uri: http://localhost:8081
          predicates:
            - Path=/orders/** 
        - id: delivery
          uri: http://localhost:8082
          predicates:
            - Path=/deliveries/**,/cancellations/**
        - id: statusview
          uri: http://localhost:8083
          predicates:
            - Path= /customerpages/**
        - id: payment
          uri: http://localhost:8084
          predicates:
            - Path=/payments/**,/paymentCancellations/**
        - id: coupon
          uri: http://localhost:8085
          predicates:
            - Path=/coupons/**,/couponCancellations/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: order
          uri: http://user29carshareorder:8080
          predicates:
            - Path=/orders/** 
        - id: delivery
          uri: http://user29carsharedelivery:8080
          predicates:
            - Path=/deliveries/**,/cancellations/**
        - id: statusview
          uri: http://user29carsharestatusview:8080
          predicates:
            - Path= /customerpages/**
        - id: payment
          uri: http://user29carsharepayment:8080
          predicates:
            - Path=/payments/**,/paymentCancellations/**
        - id: coupon
          uri: http://user29carsharecoupon:8080
          predicates:
            - Path=/coupons/**,/couponCancellations/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
